services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    volumes:
      - ./mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./app:/var/www/html
